# Generated by Django 5.1.1 on 2024-09-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boom", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="oauthtoken",
            name="profile_json",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
