# Generated by Django 5.1.1 on 2024-09-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boom", "0002_oauthtoken_profile_json"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="oauthtoken",
            name="issued_at",
        ),
        migrations.AlterField(
            model_name="oauthtoken",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="The timestamp when the token was issued."
            ),
        ),
    ]
