# Generated by Django 5.1.1 on 2024-09-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boom", "0003_remove_oauthtoken_issued_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="oauthtoken",
            name="expires_in",
        ),
        migrations.AddField(
            model_name="oauthtoken",
            name="refresh_token_expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="The expiration time of the refresh token.",
                null=True,
            ),
        ),
    ]
