# Generated by Django 5.1.1 on 2024-09-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boom", "0004_remove_oauthtoken_expires_in_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="oauthtoken",
            name="name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
